# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHBOBgFR3RCJnoqAM_GHzHzd-iPKJG83
"""

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,1,10])

plt.plot(y,'o:r')
plt.show()