# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eL4uEYbot8TdO1ynIEMR9hdN_jrecGxy
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,marker='o',ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,marker='o',ms=20,mec='r')
plt.show()